DELETE http://localhost:3001/api/contacts/640e40a926007c58c340d8c3

#### Fetch All Contacts
GET http://localhost:3001/api/contacts

### Create New Contact
POST http://localhost:3001/api/contacts
Content-Type: application/json

{
  "name": "Hercule Poirot",
  "number": "233-808-9090"
}

#### Fetch Individual Contact by Id
GET http://localhost:3001/api/contacts/640e40f726007c58c340d8d4

#### Get INFO
GET http://localhost:3001/info
